name: Deploy docs

on:
  push:
    branches:
      - main

# Adicionar permissões explícitas
permissions:
  contents: write
  pages: write

jobs:
  build-end-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - run: yarn build

    - name: Deploy storybook
      working-directory: ./apps/docs
      run: yarn deploy-storybook -- --ci --existing-output-dir=storybook-static
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}